Some more experiments

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -17,17 +17,35 @@ jobs:
         java-version: 1.8
     - name: Deploy to Bintray
       id: deploy-to-bintray
-      run: mvn deploy -s .github/bintray-settings.xml || echo "deploy failed"
+      run: mvn deploy -s .github/bintray-settings.xml || echo "deploy failed" >&2
       env:
         BINTRAY_USERNAME: ${{secrets.bintray_username}}
         BINTRAY_PASSWORD: ${{secrets.bintray_password}}
-    - name: Attach files to Release
+
+    - name: Move sources jar file
+      run: mv "target/*-sources.jar" sources.jar
+
+    - name: Move target jar file
+      run: mv "target/*.jar" target.jar
+
+    - name: Attach source jar to release
       id: upload-release-asset
       uses: actions/upload-release-asset@v1.0.1
       env:
         GITHUB_TOKEN: ${{ github.token }}
       with:
         upload_url: ${{ github.event.release.upload_url }}
-        asset_path: target/kotlin-pandoc-*.jar
+        asset_path: sources.jar
+        asset_name: kotlin-pandoc-${{ github.event.release.tag_name }}-sources.jar
+        asset_content_type: application/zip
+
+    - name: Attach target jar to release
+      id: upload-release-asset
+      uses: actions/upload-release-asset@v1.0.1
+      env:
+        GITHUB_TOKEN: ${{ github.token }}
+      with:
+        upload_url: ${{ github.event.release.upload_url }}
+        asset_path: target.jar
         asset_name: kotlin-pandoc-${{ github.event.release.tag_name }}.jar
         asset_content_type: application/zip
