ended playing with github actions

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -17,7 +17,9 @@ jobs:
         java-version: 1.8
     - name: Deploy to Bintray
       id: deploy-to-bintray
-      run: mvn deploy -s .github/bintray-settings.xml || echo "deploy failed" >&2
+      run: |
+        mvn versions:set -DnewVersion=${{ github.event.release.tag_name }}
+        mvn deploy -s .github/bintray-settings.xml || echo "deploy failed" >&2
       env:
         BINTRAY_USERNAME: ${{secrets.bintray_username}}
         BINTRAY_PASSWORD: ${{secrets.bintray_password}}
