Some more experiments

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -16,7 +16,17 @@ jobs:
       with:
         java-version: 1.8
     - name: Deploy to Bintray
-      run: mvn deploy -s .github/bintray-settings.xml
+      id: deploy-to-bintray
+      run: mvn deploy -s .github/bintray-settings.xml || echo "deploy failed"
       env:
         BINTRAY_USERNAME: ${{secrets.bintray_username}}
         BINTRAY_PASSWORD: ${{secrets.bintray_password}}
+    - name: Attach files to Release
+      id: upload-release-asset
+      uses: actions/upload-release-asset@v1.0.1
+      env:
+        GITHUB_TOKEN: ${{ github.token }}
+      with:
+        upload_url: ${{ github.event.release.upload_url }}
+        asset_path: target/kotlin-pandoc-*.jar
+        asset_name: kotlin-pandoc-*.jar
